// G3 Detectable Spells (special thanks to CamDawg, DavidW and all the other DS contributors)

ACTION_IF NOT FILE_EXISTS_IN_GAME ~fl#qpds.mrk~ BEGIN
  PRINT ~Initializing Detectable Spells installation ...~                    // let the user know that DS are being installed
  INCLUDE ~%MOD_FOLDER%/Scripts/ds/ds.tph~
  LAF detectable_spells END
  COPY_EXISTING ~sw1h01.itm~ ~override/fl#qpds.mrk~
END
